### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by legoktm** [JakubOnderka/PHP-Parallel-Lint#54] opened 2015-06-01 17:09 UTC
Hi! Today we had a user on Windows who experienced a bug that had been fixed a while back (#40), but isn't included in a release yet. Could you do a new release that includes that patch?

Thanks!

**Comment by VasekPurchart** [comment] 2015-06-02 07:51
Duplicate of #49.

**Comment by JakubOnderka** [comment] 2015-06-16 10:29
Today was released 0.9 version :-)

**Closed by JakubOnderka** 2015-06-16 10:29 UTC

**Comment by legoktm** [comment] 2015-06-19 21:41
Thank you!

**Comment by Krinkle** [comment] 2015-06-19 21:48
Thanks! :star2:
